In [1]:
import numpy as np
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
value = [3, 5]
init = tf.constant_initializer(value)
W = tf.get_variable('W', shape = [2, 1, 1], initializer = init)

In [3]:
nb_batch = 1
nb_sequence = 8
nb_channel = 1
batch = np.arange(1, 9).astype(np.float32)
batch = batch.reshape((nb_batch, nb_sequence, nb_channel))

In [4]:
inp = tf.placeholder(tf.float32, shape=[None, nb_sequence, nb_channel])
dilation_rate = 4
paddings = [[0, 0], [dilation_rate, 0], [0, 0]]
pad = tf.pad(inp, paddings)
conv = tf.nn.convolution(pad, W, strides=[1,], dilation_rate=[dilation_rate,], padding='VALID')

In [5]:
sess.run(tf.global_variables_initializer())

In [6]:
feed_dict = {inp: batch}
ret = sess.run(conv, feed_dict=feed_dict)

In [7]:
ret.shape

(1, 8, 1)

In [8]:
print(batch)

[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]
  [ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]]


In [9]:
W.eval()

array([[[ 3.]],

       [[ 5.]]], dtype=float32)

In [10]:
ret

array([[[  5.],
        [ 10.],
        [ 15.],
        [ 20.],
        [ 28.],
        [ 36.],
        [ 44.],
        [ 52.]]], dtype=float32)